# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab4308c6f210e433386a8b672dab168b007fdf5e4062e17d4391afc32176037016d442c8be0419a210f10c33e5d4cf64d3ac4ea44ddace8c8dc2244c93671d5

test:
  secret_key_base: 1860851c68a75d372116c6065c6701da0095b124777c740eeaef475e58943abe6ff086225a9ab7c326f6830cb799ce6a4c7a0ef5ea2b9bc16bb5a5ffe1d0c253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
